apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: sla-serving
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: "sla-router"
        static_configs:
          - targets: ["sla-router-service:8000"]

      - job_name: "high-model"
        static_configs:
          - targets: ["high-model-service:8001"]

      - job_name: "fast-model"
        static_configs:
          - targets: ["fast-model-service:8002"]